### ISSUE TITLE
EXT bit during exceptions?

### ISSUE THREAD

**Issue by superfury** [barotto/test386.asm#7]
In many cases, the pseudofunction error_code is invoked with a pseudovariable EXT. The value of EXT depends on
the nature of the event whose delivery encountered a nested exception: if that event is a software interrupt (INT n,
INT3, or INTO), EXT is 0; otherwise (including INT1), EXT is 1.

That's according to https://www.felixcloutier.com/x86/INTn:INTO:INT3:INT1.html

So, if I understand it correctly, errors thrown during INT (and related instructions causing an interrupt on purpose, into,INT3) clear EXT while all others set it?

So your testroutine checking for e.g. the NULL descriptor should set EXT? Or are moves and jumps that cause loading of segments also included(according to your testsuite, they aren't)?

**Comment by superfury** [comment]
So all exceptions during exceptions have the EXT bit set? So a #UD fault that throws a #GP fault will have the EXT bit set to 1(exception during earlier exception that doesn't double fault)?

**Comment by barotto** [comment]
EXT=1 if processing external interrupt or exception or if not related to current instruction.
EXT=0 if current CS:EIP caused the exception.

So if a #UD throws a #GP, the error code pushed for the #GP will have the EXT bit set to 1, because the #GP has not been thrown by the current CS:EIP.
For a confirmation on this you can see Bochs' source at BX_CPU_C::exception().
